### ISSUE TITLE
Parsing data for CanCOGeN VOC Viz Tool

### ISSUE THREAD

**Issue by Anoosha-Sehar** [nodrogluap/pokay#3]
Hi Paul, 

I am trying to parse the information in data files and came across a couple of variations in the use of separator between mutations. I was just wondering if there is a difference in interpretation of information separated by commas (,) and semi colons (;), or if it's just a typo?  
For example: 
Case1:  Mutations in the file [S_monoclonal_antibody_serial_passage_escape.txt](https://github.com/nodrogluap/pokay/blob/master/data/S_monoclonal_antibody_serial_passage_escape.txt) are separated out with comma. 
Case2: In [S_transmissibility.txt](https://github.com/nodrogluap/pokay/blob/master/data/S_transmissibility.txt) few mutations are separated out with comma, and few with semi colon. 
Case3: In [S_antibody_epitope_effects.txt ](https://github.com/nodrogluap/pokay/blob/master/data/S_antibody_epitope_effects.txt) line#357, both separators ( , ; ) are used. 
Could you please help with this?

**Comment by nodrogluap** [comment]
These have all been converted to semi-colon now.
